print("I'm Aaliyah")
print("A student of UNILAG")
print("I am a Champion")
print("I love food")
print("Python is an high level programming language")
print("Python is cool")
print("Jesus is Lord")
print("Python is as simple as ABC")
print("Python is easy to comprehend")
print("Python uses interpreter as its language translator")
print("Python is unique in its own way")
print("Python has its own syntax")
print("Python is useful in back-end")
print("Python over JavaScript anytime!")
print("Python is just a spec")
