print("My name is Aaliyah")
print("Jesus is Lord")
print("Off to Canada")
print("Off to Paris")
print("Amen!")
print(7+7)
print(18+2)
print(9+9)
print(16+4)
print(2+2)
username = input("What's your name")
print("Hello + Str(username)")